### ISSUE TITLE
Tesla Superchargers ve Filtreleme

### ISSUE THREAD

**Issue by berkesonmez** [sarjdev/back-end#7]
Merhabalar,

Haritayı incelediğimde tesla superchargerların olmadığını gördüm belki eklenebilir.
https://www.tesla.com/en_US/findus/list/superchargers/Turkey

Ayrıca filtreleme için sadece istasyon sayısı ve km yerine şarj firması, plug type ve AC/DC ⚡️ eklenebilir.

Teşekkürler.

**Comment by yusufyilmazfr** [comment]
Selam @berkesonmez, çok güzel düşünmüşsün. Plug type kısmı için efor harcamak gerekiyor açıkçası, sarj.dev kendi içerisinde farklı farklı provider'lardan besleniyor fakat hepsi de bunu sağlayamayabiliyor. Bu aralar ufak bir araya çıkacağım (biliyorsun konuyu), not aldım bu dediğini. Dönüşte zaman ayıracağım buna.

**Comment by yusufyilmazfr** [comment]
Selam @berkesonmez, Tesla'yı ekledik. :) Filtreleme için şu anlık olmasa da ilerleyen aşamalarda düşünüyoruz.
