### ISSUE TITLE
Missing city field's on data

### ISSUE THREAD

**Issue by mertssmnoglu** [sarjdev/back-end#8]
Search Suggestion tarafından gelen verilerde `highlightedText` field'ının son kelimesi city değerini içeriyor. Gelen verilerin bazılarında city olmadığı için de `highlightedText`'in son kelimesi null olarak kullancıya yansıyor.

## Örnek:
- `Awcı Motors İstanbul Avcılar, İstanbul <b>null</b>`
- `Krempark AVM Tekirdağ İnönü, Tekirdağ <b>null</b>`

Toplamda 1632 adet veride city değeri eksik gözüküyor. Veride tutarlılığı sağlamak adına adres bilgisinin son kelimesi city değeri olarak veriye eklenebilir.

**Comment by yusufyilmazfr** [comment]
Selam @mertssmnoglu, çok teşekkürler geri bildirimin için https://github.com/sarjdev/back-end/pull/9 ile çözüldü.
